version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
    #ports:
    #  - 5555:5555
    environment:
      SERVICE_PORT: 5555
      FLASK_USER: ${FLASK_USER}
      FLASK_PW_HASH: ${FLASK_PW_HASH}
    volumes:
      - /var/secure-api/share/web:/share
    networks:
      - main
    healthcheck:
      test: wget --quiet --tries=3 --spider https://chr-fr.org || exit 1
      interval: 125s
      timeout: 120s
      retries: 3

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
    volumes:
      - /var/secure-api/data/certbot/conf:/etc/letsencrypt
      - /var/secure-api/data/certbot/www:/var/www/certbot
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    networks:
      - main

  certbot-auto:
    build:
      context: ./certbot-auto
    volumes:
      - /var/secure-api/data/certbot/conf:/etc/letsencrypt
      - /var/secure-api/data/certbot/www:/var/www/certbot
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
      EMAIL_ADDRESS: $EMAIL_ADDRESS

  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - './data:/data/db'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


networks:
  main:
    driver: bridge